name: Linting
on: push

jobs:
  run_tests:
    name: Run linting checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1
      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os}}-pip-
      - name: Install dependencies
        run: pip install -r src/requirements.txt
      - name: Run Black
        run: black --check --exclude '.*/migrations/.*.py' src
      - name: Run Flake8
        run: flake8 -v src
      - name: Run isort
        run: isort --check src
